/**
 * Bundles dither.worker.ts into a single self-contained IIFE string and
 * writes it as a plain TS string constant (workerSource.generated.ts).
 *
 * Why this exists at all: `new Worker(new URL("./dither.worker.ts",
 * import.meta.url))` is the idiomatic way to reference a worker, but it
 * only resolves correctly when the SAME bundler processes both the
 * reference and the worker file in one build. For a published library,
 * downstream consumers use a bundler of their own choosing that never sees
 * dither.worker.ts — only the compiled dist/. Tried as-is, Vite's own
 * library build rewrote the reference to an absolute path scoped to *this*
 * package's own dist/assets/, which cannot resolve inside node_modules at a
 * consumer's build time (confirmed by building and inspecting the output).
 *
 * Inlining the worker's full bundled source as a string and constructing it
 * via `new Blob([source]) + URL.createObjectURL(...)` at runtime sidesteps
 * bundler-specific worker handling entirely — there is no file reference
 * for any bundler to (mis)rewrite.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "vite";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entry = resolve(root, "src/modules/dither/dither.worker.ts");
const outFile = resolve(root, "src/modules/dither/workerSource.generated.ts");

const result = await build({
  configFile: false,
  logLevel: "warn",
  build: {
    write: false,
    minify: false,
    target: "es2020",
    lib: {
      entry,
      formats: ["iife"],
      name: "__dm_dither_worker",
      fileName: () => "worker.js",
    },
  },
});

// vite's build() returns an array of RollupOutput (one per build target).
const chunk = result[0]?.output.find((o) => o.type === "chunk");
if (!chunk) throw new Error("build-worker: no output chunk produced");

const source = chunk.code;
const banner =
  "// GENERATED by scripts/build-worker.mjs — do not edit by hand.\n" +
  "// Bundled classic-script source for dither.worker.ts, embedded as a\n" +
  "// string so runDither.ts can construct it via a Blob URL instead of a\n" +
  "// `new Worker(new URL(...))` reference (see this script's own header\n" +
  "// comment for why that reference doesn't survive being republished).\n";
const contents = `${banner}export const WORKER_SOURCE = ${JSON.stringify(source)};\n`;

if (!existsSync(dirname(outFile))) mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, contents);

console.log(`worker: bundled ${(Buffer.byteLength(source) / 1024).toFixed(1)}kb -> ${outFile}`);
